// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bhcobewqjkvptmojaoep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJoY29iZXdxamt2cHRtb2phb2VwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3NjUxNzgsImV4cCI6MjA3MTM0MTE3OH0.U9gvN-cQRJsvwmdLga1xf2sSYpTzwCyX2PEoG-Dpu-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});